### ISSUE TITLE
JUS-95 Twitter 모아보기 및 나머지 기능 확인후 추가해야함

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#131]
* 모아보기 및 나머지 기능들에 대한 처리가 필요함
* Twitter 기능에 대한 전반적인 테스트도 수행

**Comment by kimalec** [comment]
seankim  added a comment - 25/Dec/14 9:20 AM
postid를 통해 댓글을 가져오는 대신에 retweet 개수와 favorite 개수를 표시해줘야함

Sean Kim added a comment - 25/Dec/14 9:52 AM
user_timeline으로 retweet_count와 favorite_count를 알 수 있음
retweet_count=0, favorite_count=0
/bot_posts/new/:blog_id 및 /bot_comments/:blogID/:postID 가 필요한지 생각해봐야겠음

Sean Kim added a comment - 25/Dec/14 10:13 AM
댓글이 없으므로 가능하다면 twitter의 reply(팝업)와 favorite 기능을 추가 하는 것도 괜찮은 것 같음

Sean Kim added a comment - 26/Dec/14 9:27 AM - edited
twitter에는 하나의 id에 대한 정보을 얻어오는 api가 없기에 user_timeline을 얻어올때 미리 디비에 저장하는 방법밖에 현재 찾을 수 없기에 db에 저장하는 루틴으로 변경
retweet_count 와 like_count를 postDB에 추가함

Sean Kim added a comment - 26/Dec/14 9:32 AM
다른 블로그와는 달리 모아보기시에 추가적으로 blog api를 호출하는 대신에 디비에 저장된 부분으로만 모아보기를 처리해야됨
blog_comments는 존재하지 않기에 처리할 필요가 없음 (twitter.js에서 삭제해야함)
retweet_count와 like_count 뿌려주고 reply에 대한 처리를 할지 결정해야함
/bot_posts/new/:blog_id 에 대한 호출은 다른 블로그 처리 루틴을 확인후에 처리해야함

Sean Kim added a comment - 27/Dec/14 10:12 AM
postDb에서 replies(retweet_count, like_count) 가져오는 방식으로 변경
blogID가 undefined되는 문제와 retweet, like cnt 화면에 뿌리지 못하는 에러 발생(디버깅 해야함)

Sean Kim added a comment - 28/Dec/14 1:36 AM
blogID를 req.params.blog_id 값으로 변경함으로 제대로된 값으로 표시

Sean Kim added a comment - 28/Dec/14 2:32 AM
postid가 undeiflend이고, replies(retweet_count, like_count)를 제대로 가져오지 못함
front-end, back-end 다 살펴보아야함
front-end
```javascript
20controller.js:226 push post_id=undefined
21angular.js:9899 TypeError: Cannot read property 'toString' of undefined
    at getPost (http://www.justwapps.com/javascripts/controller.js:211:110)
    at http://www.justwapps.com/javascripts/controller.js:252:35
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.js:7976:11
    at wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.js:11408:81)
    at wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.js:11408:81)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.js:11494:26
    at Scope.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.js:12518:28)
    at Scope.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.js:12330:31)
    at Scope.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.js:12622:24)
    at done (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.js:8234:45)
```
back-end
```javascript
debug:  providerName=twitter, blogID=86051098, postID=undefined, replies=[, ]
```

Sean Kim added a comment - 29/Dec/14 6:24 AM
기존 send_post.id = raw_post.ID; 이 아닌 기존 db에 저장된 형태로 send_data를 전달이 되지 못했음
전달 형태 값 디버깅을 통해 에러 해결 및 postID 값 정상 출력, replies 의 retweet_count 및 like_count 정상 출력

Sean Kim added a comment - 04/Jan/15 4:59 AM
모아보기 기능 완료 후 Resolve함

Alec Kim added a comment - 04/Jan/15 9:37 PM
구현되고 나서 태클 걸게 생겼네요. ㅠ.ㅠ
우선 다른 replies정보는 일부러 postDb에 넣지 않고 있는데, twitter에서 바로 가지고 올 방법은 없는건가요?
이게 항상 갱신되어야 하는데, db에 넣고 정기적으로 업데이트 하는 것이 좀 부담인듯 해서요.
또 하나는 models에 있는 XXXdb.js는 데이터 모델이기 때문에 provider 정보 같은 특정 조건은 넣지 않아야 합니다. 또한 함수 조차도 사실 최소한으로 유지 하는 것이 좋습니다.
좀 살펴보니 replies를 postDb에 저장하지 않는다면 이부분도 필요하지는 않는 것 같습니다.

Sean Kim added a comment - 11/Jan/15 7:20 AM
retweet와 like에 대한 post 하나에 대한 데이터를 user_timeline count를 1로 셋팅한후에 max_id로 tweet데이터 한 개씩 얻어 올수 있을 것으로 예상됨.
기존 방식대로 db에 데이터를 저장하지 않고 이방법으로 변경 작업 해야함

Sean Kim added a comment - 11/Jan/15 7:21 AM
retweet 및 like 데이터를 처리하기 위한 구조 변경

Sean Kim added a comment - 12/Jan/15 7:40 AM
구조 변경을 위해 /bot_posts/:blog_id 시에 retweet 및 like db 저장 부분 삭제
count 1을 이용한 user_timeline api를 통해 각 post에대한 데이터 정상적으로 가져오고 retweet & like 정상 표시됨

Sean Kim added a comment - 13/Jan/15 8:28 AM
/bot_posts/new/:blog_id 기능 추가해야함
테스트 후 동작방식에 대한 이해 후에 기존 코드 수정으로 방향 잡아야함

Sean Kim added a comment - 15/Jan/15 10:20 PM
BlogBot._requestPostContent에서 new를 처리함
BlogBot.task -> _getAndPush -> _pushPostsToBlogs -> _sendPostToBlogs -> _requestPostContent
_requestPostContent에서 각 provider에 대한 new를 처리
2분마다 한 번씩 blogBot.task(); 를 호출하여 Blog들을 Sync 함

Sean Kim added a comment - 18/Jan/15 12:04 AM
30초로 변경후 디버깅
_pushPostsToBlogs 에서 진행되지 않음
recvPosts.posts 가 값이 없음
Twitter : /bot_posts/86051098?after=2015-01-12T14:37:36.426Z&userid=54b27b0c6bc6a10000c34e53
twitter가 호출하는 방식이 틀리기에 recvPost.posts가 값이 없음.
그래서 requestPost를 twitter일시에는 recursive로 변경. => _sendPostToBlogs 까지 진행됨
그러나 계속 반복됨됨

Sean Kim added a comment - 18/Jan/15 8:10 PM
twitter.js의 router /bot_posts/new/:blog_id 호출됨
upload post api를 통해 upload 기능을 추가해야함.

Sean Kim added a comment - 21/Jan/15 11:28 PM
wordpress에 sync가 반복되어 500개 이상의 글이 등록되어 있음.
디버그의 어려움 또는 버그 이므로 직접 다 삭제함
테스트 검증을 위해 로컬 호스트의 db도 모두 삭제함
결론적으로 twitter의 new는 동작하지 않은 것으로 보임. 실제 twitter에도 글 등록이 되지 않았음
글 등록 twitter api는 statuses/update.json?status=$(comment) 내용이 post로 보임 테스트중

Sean Kim added a comment - 25/Jan/15 12:35 AM
wordpress와 twitter에 하나의 그룹으로 묶고, wordpress에 새로운 글을 올려도, new routine을 타지 않음
디버깅을 해보니, 항상 _sendPostToBlogs에서 skip됨
현재 group이 정상적으로 데이터가 들어간건지 잘 모르겠음.. 동환님께 내일 물어봐야겠음.

Sean Kim added a comment - 25/Jan/15 8:59 PM
단일 post(new)에 대한 검증 완료 되었지만 group시에 new 검증 필요함
wordpress 글 post 후에 twitter가 blogsync(new) 되는 루틴으로 테스트
반복적으로 글이 sync 되는 문제점 확인해야함

Sean Kim added a comment - 27/Jan/15 11:08 PM - edited
Twitter new post 시 아래 에러 발생
```javascript
{"errors":[{"message":"Could not authenticate you","code":32}]}
```
단일로 테스트시에는 정상적이나 Sync로 동작시키면 위에러가 발생됨....

Sean Kim added a comment - 27/Jan/15 11:54 PM
특수문자로 인한 에러 임
encodeURIComponent를 사용하면 정상 동작함

Sean Kim added a comment - 30/Jan/15 12:04 AM
같은 데이터들이 계속적으로 postDB에 추가됨...
wordpress와 twitter를 그룹핑했을 때 wordpress에만 2분마다 같이 데이터가 추가됨
아래 조건을 만족하지 못해 postDb.addPost() 되는 것 처럼 보임
```javascript
if (postDb.findPostByPostIdOfBlog(recvPosts.provider_name, recvPosts.blog_id, newPost.id)) {
            log.debug('this post was already saved - provider ' + recvPosts.provider_name + ' blog ' +
                            recvPosts.blog_id + ' post ' + newPost.id);
            continue;
        }
```

Sean Kim added a comment - 04/Feb/15 12:23 AM
reculsive 함수를 쓰지 않고 기존에 after options으로 처리
local commit 완료후 BlogSyncer/master와 merge
conflict 제거후 테스트
변경된 부분으로 아래에러 발생 ㅠㅠ - provider가 제대로 들어오지 않음
```javascript
/Users/mis2010/workjs/BlogSyncer/routes/twitter.js:235
WITTER_API_URL+"/statuses/user_timeline.json?screen_name="+ provider.providerI
                                                                    ^
TypeError: Cannot read property 'providerId' of undefined
    at /Users/mis2010/workjs/BlogSyncer/routes/twitter.js:235:88
    at Promise.<anonymous> (/Users/mis2010/workjs/BlogSyncer/routes/userManager.js:166:20)
    at Promise.<anonymous> (/Users/mis2010/workjs/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/Users/mis2010/workjs/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/mis2010/workjs/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Object.cb (/Users/mis2010/workjs/BlogSyncer/node_modules/mongoose/lib/query.js:1146:30)
    at Object._onImmediate (/Users/mis2010/workjs/BlogSyncer/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

Sean Kim added a comment - 10/Feb/15 12:06 AM
_findProviderByUserId 두번째 인자에 TWITTER_PROVIDER 대신에 TWITTER_API_URL 들어갔음
수정후 정상동작

 Sean Kim added a comment - 10/Feb/15 12:17 AM
new 기능 버그 및 merge 후 에러 수정 확인으로 fixed 처리함
