### ISSUE TITLE
JUS-106 test unit 에러 수정하기.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#154]
아래와 같이 unit test시에 에러 발생함.

/usr/local/bin/mocha /usr/local/lib/node_modules/mocha/bin/_mocha --ui bdd --reporter /Applications/WebStorm.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js /Users/aleckim/WebstormProjects/BlogSyncer/test

ReferenceError: log is not defined
    at model.postSchema.methods.addPostInfo (/Users/aleckim/WebstormProjects/BlogSyncer/models/postdb.js:133:5)
    at Context.<anonymous> (/Users/aleckim/WebstormProjects/BlogSyncer/test/test_postdb.js:47:20)
    at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:250:21)
    at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:243:7)
    at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:373:10)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:451:12
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:298:14)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:308:7
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:246:23)
    at Object._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate [as _immediateCallback] (timers.js:345:15)

**Comment by kimalec** [comment]
Alec Kim added a comment - 25/Jan/15 6:10 PM
#140 JUS-97 수정에 따른 사이드임.
