### ISSUE TITLE
JUS-113 블로그 Sync시 이미지에 대한 처리를 한다.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#167]
* BlogBot이 Sync동작을 할때 이미지에 대한 처리도 한다.
** Sync를 블로그 Register후 BlogBot이 동작시에 이미지가 있는 post를 확인
** 이미지가 있는 Post의 image 경로를 parsing
** 이미지를 가져와서 db에 temp로 저장
** sync 될 target blog에 image upload후 url을 Get
** sync될 url을 저장
** 모아보기에서 이미지에 대한 처리를 한다.

**Comment by kimalec** [comment]
Sean Kim added a comment - 14/Feb/15 11:46 PM
이미지 테스트가 가능한 wordpress와 tistory로 먼저 구현한다.

Sean Kim added a comment - 01/Mar/15 5:29 PM
duplicate를 하기에 블로그 마다 다른 image URL이 나와야 함.

Sean Kim added a comment - 01/Mar/15 5:32 PM
먼저 파일 형태로 저장 후 iostream(??)을 사용한다.
http://nodeqa.com/sitemap# 에서 stream부분 참고

Sean Kim added a comment - 01/Mar/15 5:59 PM
photos의 object를 메모리에 저장 후 upload 해야 함
``` javascript
 image_permalink: 'http://seanshiningbluekim.tumblr.com/image/112396288087',
       photos: [Object],
       can_reply: false },
```

Sean Kim added a comment - 05/Mar/15 11:24 PM
Tumblr에 사진을 올려서 Sync시 WordPress에 저장을 시도
image 시에 url을 통하여 데이터를 파일로 저장시도
아래 예제를 변형 사용예정
``` javascript
var http = require('http')
  , fs = require('fs')
  , options
options = {
    host: 'www.google.com'
  , port: 80
  , path: '/images/logos/ps_logo2.png'
}
var request = http.get(options, function(res){
    var imagedata = ''
    res.setEncoding('binary')
    res.on('data', function(chunk){
        imagedata += chunk
    })
    res.on('end', function(){
        fs.writeFile('logo.png', imagedata, 'binary', function(err){
            if (err) throw err
            console.log('File saved.')
        })
    })
})
```

Sean Kim added a comment - 08/Mar/15 11:46 PM
적용을 위해 전달할 url 에러 발생
raw_post.photos.original_size.url 여기서 에러가 남
```
debug: [ { caption: '',
    alt_sizes: [ [Object], [Object], [Object], [Object] ],
    original_size: 
     { width: 320,
       height: 480,
       url: 'http://40.media.tumblr.com/3c8e2ea42dd618d6a3d2b57ac5de15b9/tumblr_nkqtn7CUGB1u3skrko1_400.png' } } ] cName=tumblr, fName=_pushPostsFromTumblr
TypeError: Cannot read property 'url' of undefined
    at _pushPostsFromTumblr (/Users/mis2010/workjs/BlogSyncer/routes/tumblr.js:375:56)
    at /Users/mis2010/workjs/BlogSyncer/routes/tumblr.js:497:13
    at Request._callback (/Users/mis2010/workjs/BlogSyncer/node_modules/tumblr.js/lib/tumblr.js:243:12)
    at Request.self.callback (/Users/mis2010/workjs/BlogSyncer/node_modules/tumblr.js/node_modules/request/main.js:122:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/mis2010/workjs/BlogSyncer/node_modules/tumblr.js/node_modules/request/main.js:661:16)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/mis2010/workjs/BlogSyncer/node_modules/tumblr.js/node_modules/request/main.js:623:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
```

Sean Kim added a comment - 10/Mar/15 11:48 PM
'raw_post.photos[ 0 ].original_size.url' 을 통해 일단 google logo를 저장함
```
File saved.
debug: http://36.media.tumblr.com/fa49ffb29b0a9137cb09b99aee5c5a6b/tumblr_nl03asqJxV1u3skrko1_400.png cName=tumblr, fName=_pushPostsFromTumblr
```
url을 파싱하여 options의 host, path에 밀어 넣고, 올린이미지를 저장해야 함
tmp 디렉토리를 만들어 저장하고, sync 후에 삭제 하는 루틴으로 구현해야함

Sean Kim added a comment - 14/Mar/15 5:33 PM
phpjs를 사용하여 strtok를 사용하여 mailUrl과 subUrl을 구분하여 function내에 입력해야됨

Sean Kim added a comment - 14/Mar/15 5:43 PM
아래 코드로 host와 path를 나눔
``` javascript
    var php = require('phpjs');
    var hostStr = php.strtok(imgUrl, "/");
    var pathStr = php.strtok("");
```
아래 sample 결과과 나옴. 이 부분을 sync시 적용하면 될 것 같음
```
: samve image : www.justwapps.com/images/test.png
info: mainURL image : www.justwapps.com
info: subUrl image : images/test.png
```

Sean Kim added a comment - 16/Mar/15 10:38 PM
underscore를 확인해 보았지만 string을 control하는 함수는 보이지 않음
phpjs를 사용하지 않고, javascript 기본 함수인 split 을 응용하여 원하는 결과를 얻음
```
    var result = imgUrl.split("/");
    var hostStr = result[0];
    result = imgUrl.split(hostStr);
    var pathStr = result[1];
```

Sean Kim added a comment - 19/Mar/15 10:54 PM
아래와 같은 url은 제대로 파싱 되지 않음.. 다른 방식을 사용해야 될듯...
```
debug: http://36.media.tumblr.com/ad628a8a0b37c81aca43fece4f46d20f/tumblr_nlgp5jenHR1u3skrko1_400.jpg cName=tumblr, fName=saveImageFromURL
debug: { host: 'http:',
  port: 80,
  path: '//36.media.tumblr.com/ad628a8a0b37c81aca43fece4f46d20f/tumblr_nlgp5jenHR1u3skrko1_400.jpg' } cName=tumblr, fName=saveImageFromURL
```

Sean Kim added a comment - 19/Mar/15 11:22 PM
nodejs url api를 사용 ( https://nodejs.org/docs/latest/api/url.html )
``` javascript
    var hostStr = url.parse(imgUrl).hostname;
    var portStr = url.parse(imgUrl).port;
    var pathStr = url.parse(imgUrl).pathname;
    options = {
        host: hostStr
        , port: portStr
        , path: pathStr
    };
```

Alec Kim added a comment - 14/Apr/15 11:11 PM
Request can also pipe to itself. When doing so, content-type and content-length are preserved in the PUT headers.
``` javascript
request.get('http://google.com/img.png').pipe(request.put('http://mysite.com/img.png'))
```
Request emits a "response" event when a response is received. The response argument will be an instance of http.IncomingMessage.
``` javascript
request
  .get('http://google.com/img.png')
  .on('response', function(response) {
    console.log(response.statusCode) // 200
    console.log(response.headers['content-type']) // 'image/png'
  })
  .pipe(request.put('http://mysite.com/img.png'))
```

Sean Kim added a comment - 18/Apr/15 12:03 AM
블로그 sync시 이미지 파일에 대한 temp 파일 저장에 대한 diff 파일
```
diff -r BlogSyncer/package.json BlogSyncer_150412_2_last/package.json
53c53,54
<     "q": "~1.1.2"
---
>     "q": "~1.1.2",
>     "underscore": "1.4.4"
diff -r BlogSyncer/routes/blogbot.js BlogSyncer_150412_2_last/routes/blogbot.js
101c101
<     log.debug(providerName, meta);
---
>     log.debug(rcvPosts, meta);
272a273
> 
284a286
> 
1168c1170
<         //log.debug(body.toString(), meta);
---
>         log.debug(body.toString(), meta);
1314a1317
>     var postType = 0;   // 0 : text, 1 : image, 2 : movie
1319a1323,1327
>     if(post.content[0].alt_sizes) {
>         log.debug("post type is image !!!", meta);
>         postType = 1;
>     }
> 
1335a1344
> 
diff -r BlogSyncer/routes/tumblr.js BlogSyncer_150412_2_last/routes/tumblr.js
15a16
> var url = require('url');
283a285,327
> function saveImageFromURL(imgUrl) {
>     var meta = {};
> 
>     meta.cName = "tumblr";
>     meta.fName = "saveImageFromURL";
> 
>     var http = require('http')
>         , fs = require('fs')
>         , options
> 
>     log.debug(imgUrl, meta);
> 
>     var hostStr = url.parse(imgUrl).hostname;
>     var portStr = url.parse(imgUrl).port;
>     var pathStr = url.parse(imgUrl).pathname;
> 
>     options = {
>         host: hostStr
>         , port: portStr
>         , path: pathStr
>     };
> 
>     log.debug(options, meta);
> 
>     var request = http.get(options, function(res){
>         var imagedata = '';
>         res.setEncoding('binary');
> 
>         res.on('data', function(chunk){
>             imagedata += chunk;
>         });
> 
>         res.on('end', function(){
>             fs.writeFile('tempImg', imagedata, 'binary', function(err){
>                 if (err) throw err
>                 console.log('File saved.');
>             })
>         })
> 
>     })
> }
> 
> 
299a344,347
>     var meta={};
> 
>     meta.cName = "tumblr";
>     meta.fName = "_pushPostsFromTumblr";
339a388,390
> 
>                 saveImageFromURL(raw_post.photos[0].original_size.url);
> 
404,405c455
< 
<     log.debug("tumblr: "+ req.url + ' : this is called by bot');
---
>     var meta={};
411a462,467
>     meta.cName = "tumblr";
>     meta.fName = "/bot_posts/:blog_id";
>     meta.userId = userId;
> 
>     log.debug(req.url, meta);
> 
449d504
<             //log.debug(response);
523a579
>     log.debug("new ===> " + req );
diff -r BlogSyncer/routes/twitter.js BlogSyncer_150412_2_last/routes/twitter.js
562a563,566
>     if(!response) {
>         return;
>     }
> 
diff -r BlogSyncer/routes/wordpress.js BlogSyncer_150412_2_last/routes/wordpress.js
461a462,463
>     var meta = {};
>     var userId = userMgr._getUserId(req, res);
463c465,470
<     log.debug('Wordpress ' + req.url);
---
>     meta.cName = "wordpress";
>     meta.fName = "/bot_posts/new/:blog_id";
>     meta.userId = userId;
> 
>     log.debug(req.url, meta);
>     log.debug("new ===> " + req.query.postType, meta );
471a479,482
>     if(req.query.postType == 1) {    // image
>         req.body = getImageFile();
>     }
> 
Only in BlogSyncer_150412_2_last: tempImg
```

**Comment by kimalec** [comment]
고려할 것이 여러가지임.
image, media, sound를 고려해야 하고, 사진을 클릭하면 새창으로 크게 그리는 걸 고려하여 window사이즈 맞추어서 재조정하는 내용.
img 같은 tag말고 object도 고려해야 한다.

**Comment by kimalec** [comment]
img src로 소스를 찾고, 다시 한번더 돌아서 img src와 같은 문자열의 위치를 가지고 변환시킨다.

두번 돌아야 하지만 DOM Tree를 형성하는 것보다 더 효율적일듯.

추가 처리 해야 할 사항 : url 뒤에 추가 파라미터 값이 있는 경우가 있다.
```
https://wizardfactory.files.wordpress.com/2015/02/ec8aa4ed81aceba6b0ec83b7-2015-02-08-17-28-37.png?w=1024&#038;h=475
```

**Comment by kimalec** [comment]
DOM Tree형성하지 않고, 앞의 방법대로 우선 img src uri를 뽑은 다음에 페이지내의 링크전환할때, 동일한 string을 찾아서 바꿔 버리는 것이 더 효율적으로 보임.

**Comment by kimalec** [comment]
아래의 예제가 파일 전송이 완료되었음에도 불구하고 정지되지 않아 timed out이 발생함.
```javascript
var formData = {
                file:  request(fileUrl)
            };

            var options = {
                headers: {
                    "authorization": "Bearer " + accessToken
                },
                formData: formData
            };

            request.post(uploadUrl, options, function (err, res, body) {
                console.log('REQUEST RESULTS:', err, res.statusCode, body);
                done();
            });
```

**Comment by kimalec** [comment]
linux에서도 동일한 문제가 발생하는 것으로 보아 os문제는 아닌듯함.  Content-Length가 좀 문제가 있어 보이긴 함. kakao말고 다른 것도 확인해볼 필요가 있을듯함.

**Comment by kimalec** [comment]
needle을 통해 wordpress에 업로드 성공하였음.

**Comment by kimalec** [comment]
#291 참고하여 form 작성하였지만 여전히 timeout발생함.

```javascript
var newForm = new FormData();

newForm.append('file', fs.createReadStream(filepath), {filename: 'ttt.jpg', contentType: 'image/jpg', knownLength: 57216});
//newForm.append('file', fs.createReadStream(filepath));

newForm.getLength(function(err,length){
    console.log('content length : ' + length);

    var r = request.post(url, {
        json: true,
        multipart: true,
        headers: {
            authorization: "Bearer " + accessToken,
        }
    }, function(err, res, body) {
        console.log(body)
    });

    r._form = newForm;
});
```

응답 결과
```javascript
{ request: 
   { debugId: 1,
     uri: 'https://kapi.kakao.com/v1/api/story/upload/multi',
     method: 'POST',
     headers: 
      { authorization: 'Bearer in_C87U6UqfY1gzpO__Ai-KeqPDTg45Qk7_-WqwQQjQAAAFOh9E9Yw',
        host: 'kapi.kakao.com',
        accept: 'application/json',
        'content-type': 'multipart/form-data; boundary=--------------------------313265400766463405915429',
        'content-length': 57418 } } }
{ response: 
   { debugId: 1,
     headers: 
      { date: 'Mon, 13 Jul 2015 14:47:56 GMT',
        server: 'Apache',
        'content-type': 'application/json;charset=UTF-8',
        'content-length': '51',
        connection: 'close' },
     statusCode: 400,
     body: { code: -603, msg: 'Timed out uploading an image.' } } }
```

**Comment by kimalec** [comment]
stackoverflow에 자문을 구하기 위해서 sample을 만드는 도중에 file upload가 되어버렸다. 
file upload하는 주요 모듈인 form-data version의 변화도 없는 것 같은데 성공하였다. ㅋ

```javascript
var url = "https://kapi.kakao.com/v1/api/story/upload/multi";
var filepath = __dirname + '/8947529877_1.jpg';

var formData = {
    file: fs.createReadStream(filepath)
};

var options = {
    headers: {
        "authorization": "Bearer " + accessToken,
    },
    formData: formData
};

request.post(url, options, function optionalCallback(err, httpResponse, body) {
    if (err) {
        return console.error('upload failed:', err);
    }
    console.log('Upload successful!  Server responded with:', body);
});
```

결과
```
$ node app.js 
{ request: 
   { debugId: 1,
     uri: 'https://kapi.kakao.com/v1/api/story/upload/multi',
     method: 'POST',
     headers: 
      { authorization: 'Bearer 3oJddVCEKO9DFbAZvA3KgOnzNPy-wwK61ugtpqwQQjQAAAFOtLoMUA',
        host: 'kapi.kakao.com',
        'content-type': 'multipart/form-data; boundary=--------------------------426172366470586056202173',
        'content-length': 57430 } } }
{ response: 
   { debugId: 1,
     headers: 
      { date: 'Wed, 22 Jul 2015 08:33:24 GMT',
        server: 'Apache',
        'content-type': 'application/json;charset=UTF-8',
        'content-length': '73',
        connection: 'close' },
     statusCode: 200,
     body: '["/CKBrm/hyfPsUzodS/YDXPnsrpCSVkYiidGwf7u0/img.jpg?width=200&height=288"]' } }
Upload successful!  Server responded with: ["/CKBrm/hyfPsUzodS/YDXPnsrpCSVkYiidGwf7u0/img.jpg?width=200&height=288"]
```
