### ISSUE TITLE
JUS-114 tumblr에서 글이 없는 경우에 죽는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#168]
tumblr에서 글이 없는 경우에 죽는 문제.

{code}
2015-02-15T05:40:42.306943+00:00 app[web.1]: debug: tumblr: /bot_posts/hajihong?after=2015-02-05T13:11:25.647Z&userid=54c9c514aacc280c006a6a72 : this is called by bot
2015-02-15T05:40:42.449124+00:00 app[web.1]: TypeError: Cannot read property 'blog_name' of undefined
2015-02-15T05:40:42.449129+00:00 app[web.1]:     at Request._callback (/app/node_modules/tumblr.js/lib/tumblr.js:243:12)
2015-02-15T05:40:42.449131+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/tumblr.js/node_modules/request/main.js:122:22)
2015-02-15T05:40:42.449127+00:00 app[web.1]:     at /app/routes/tumblr.js:642:50
2015-02-15T05:40:42.449133+00:00 app[web.1]:     at Request.emit (events.js:98:17)
2015-02-15T05:40:42.449136+00:00 app[web.1]:     at Request.emit (events.js:117:20)
2015-02-15T05:40:42.449137+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/tumblr.js/node_modules/request/main.js:623:14)
2015-02-15T05:40:42.449140+00:00 app[web.1]:     at _stream_readable.js:944:16
2015-02-15T05:40:42.449142+00:00 app[web.1]:     at process._tickCallback (node.js:442:13)
2015-02-15T05:40:42.476230+00:00 app[web.1]: 
2015-02-15T05:40:42.449135+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/tumblr.js/node_modules/request/main.js:661:16)
2015-02-15T05:40:42.449139+00:00 app[web.1]:     at IncomingMessage.emit (events.js:117:20)
{code}

**Comment by kimalec** [comment]
post를 가지고, 와서 전달할 때, blog_name을 posts\[0\].blog_name으로 가지고 오는데, 글이 한개도 없는 경우에 거기서 에러가 발생함.
``` javascript
            send_data.provider_name = TUMBLR_PROVIDER;
            send_data.blog_id = response.posts[0].blog_name;
```
아래와 같이 전달받은 blog정보에서 name을 가지고 오게 변경.

``` javascript
send_data.blog_id = response.blog.name;
```
