### ISSUE TITLE
JUS-124 tumblr, kakao stroy, Facebook link post  api 추가하기.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#182]
tumblr, kaka story, twitter, Facebook 등 link post가 필요한 provider에 대하여 rest api 추가.

**Comment by kimalec** [comment]
Alec Kim added a comment - 26/Mar/15 11:06 PM
kakao stroy의 link posting 설명 : https://developers.kakao.com/docs/restapi#카카오스토리-포스팅-링크

Alec Kim added a comment - 28/Mar/15 11:27 PM
twitter의 경우에는 blogsync의 twitter.js에서 적절하게 모양을 만들어서 넣으면 좋을 것을 생각됨.
tumblr를 link post를 지원하고 있지만, 일반적인 text post도 지원하므로 text를 사용하면 됨.
kakao story와 facebook은 맞는 api로 제작해야 할 것으로 보임.
kakao story의 경우에는 linkinfo 라는 request api를 통하여 정보를 자신이 원하는 모양으로 만들어서 post하기를 원함.

Alec Kim added a comment - 29/Mar/15 7:51 PM
kaka story link post 구현 중.
문제1. title이 없는 경우에 post db 저장되지 않아서 다음 루틴에서 새로운 post로 인식됨.

Alec Kim added a comment - 29/Mar/15 10:56 PM
_cbAddPostInfoToDb()에서는 글 쓰기를 한 post 정보를 바탕으로 postdb를 찾아서 넣도록 한다.

Alec Kim added a comment - 04/Apr/15 9:58 AM
_getAndPush에 대한 sequence diagram 추가

Alec Kim added a comment - 05/Apr/15 3:05 PM
tumblr -> kakao link post 동작 확인 완료.
groupInfo에 맞추어서 동작하게 수정 예정.
  
Alec Kim added a comment - 12/Apr/15 4:04 PM
tumblr에 link로 올라온 글을 tumblr에 post로 넘어가면서 죽는 문제가 발생함.
```javascript
debug: tumblr: /bot_posts/new/wizardfactory?userid=5520fb4783747d1d1cf3a98f&postType=post : this is called by bot
debug: https://kapi.kakao.com/v1/api/story/linkinfo?url=http://kimalec.tumblr.com/post/116183978450

/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/node_modules/request/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:41
      stream.on('data', this._checkDataSize.bind(this));
             ^
TypeError: Object web has no method 'on'
    at FormData.CombinedStream.append (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/node_modules/request/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:41:14)
    at FormData.append (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/node_modules/request/node_modules/form-data/lib/form_data.js:33:3)
    at Object.TumblrClient._post (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/lib/tumblr.js:193:12)
    at Object.calls.postCreation [as text] (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/lib/tumblr.js:35:12)
    at module.exports (/Users/aleckim/WebstormProjects/BlogSyncer/routes/tumblr.js:584:16)
    at Promise.UserMgr._findProviderByUserId (/Users/aleckim/WebstormProjects/BlogSyncer/routes/userManager.js:230:9)
    at Promise.onResolve (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
Process finished with exit code 8
```

**Comment by kimalec** [comment]
twitter의 경우에 media에 대한 설정은 link는 없어 보임.
twitter가 글자 길이의 대한 제약이 있으므로, url축약은 해야 할 것 보임.
https://dev.twitter.com/rest/reference/post/statuses/update

facebook은 해야 함.

**Comment by kimalec** [comment]
twitter나 kakao의 경우 photo posting은 upload만 지원함.
kakao의 경우에는 link posting을 지원하지만,  twitter는 그런거 없음.

**Comment by kimalec** [comment]
Facebook link posting feature 추가하였음.  aaad76c
