### ISSUE TITLE
JUS-126 tumblr link post를 tumblr에 text post할 때 죽는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#186]
사용자가 tumblr에 link post를 하면, 그것을 text로 다른 tumblr blog에 post하면 죽는 문제가 발생함.

 author: {u'displayName': u'Alec Kim', u'name': u'AlecKim', u'self': u'http://jira.wizardfactory.net/rest/api/2/user?username=AlecKim', u'avatarUrls': {u'24x24': u'http://www.gravatar.com/avatar/534d3ca635b6faf9642f2b948cedcb51?d=mm&s=24', u'16x16': u'http://www.gravatar.com/avatar/534d3ca635b6faf9642f2b948cedcb51?d=mm&s=16', u'48x48': u'http://www.gravatar.com/avatar/534d3ca635b6faf9642f2b948cedcb51?d=mm&s=48', u'32x32': u'http://www.gravatar.com/avatar/534d3ca635b6faf9642f2b948cedcb51?d=mm&s=32'}, u'emailAddress': u'kimalec7@gmail.com', u'active': True}
content: http://jira.wizardfactory.net/secure/attachment/10902/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA+2015-04-13+08.17.39.png
created: 2015-04-12T23:39:51.000+0000
filename: 스크린샷 2015-04-13 08.17.39.png
id: 10902
mimeType: image/png
self: http://jira.wizardfactory.net/rest/api/2/attachment/10902
size: 54197
thumbnail: http://jira.wizardfactory.net/secure/thumbnail/10902/_thumb_10902.png

**Comment by kimalec** [comment]
Alec Kim added a comment - 13/Apr/15 8:56 AM
그림이 없는 경우에는 죽지는 않지만 정보를 제대로 표시하지 못함.
link post의 경우에는 link를 지원하는 provider의 경우에는 link로 전달하는 것이 맞을 것으로 보임.
그렇다면, post(text)만 지원하는 경우에 방법 모색이 필요함.
![2015-04-13 08 55 07](https://cloud.githubusercontent.com/assets/6895272/7340411/1d0a67d0-ecc8-11e4-9582-dd91ba2bdabf.png)

의 경우에는 코드 상에 문제가 있었음.
post해야할 글의 type이 link이면 아래의 코드에 의해서 내용이 변경되어 들어감.
``` javascript
 case "link":
                send_post.title = raw_post.title;
                if (is_body) {
                    send_post.content = "url : "+raw_post.url+" description : " + raw_post.description;
                }
```

Alec Kim added a comment - 4 days ago
아래와 비슷한 메세지가 나옴.
```
/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/lib/tumblr.js:212
    if (options[choices[i]]) {
               ^
TypeError: Cannot read property 'body' of undefined
    at requireValidation (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/lib/tumblr.js:212:16)
    at new <anonymous> (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/lib/tumblr.js:30:7)
    at /Users/aleckim/WebstormProjects/BlogSyncer/routes/tumblr.js:539:24
    at Promise.<anonymous> (/Users/aleckim/WebstormProjects/BlogSyncer/controllers/userManager.js:227:9)
```

Alec Kim added a comment - 4 days ago
``` javascript
var postFunc;
        if (postType === "post") {
            postFunc = client.text;
        }
        else if (postType === "link") {
            postFunc = client.link;
        }
        else {
            //need to refactoring make a error object;
            var error = new Error("postType was undefined");
            log.error(error, meta);
            return res.status(500).send(error);
        }
        postFunc(blog_id, options, function (error, response) {
```
위와 같이 하면 아래의 부분에서 _post를 찾지 못함.
``` javascript
  postCreation: function (type, requireOptions, acceptsData) {
    return function (blogName, options, callback) {
      requireValidation(options, requireOptions);
      options.type = type;
      if (!acceptsData) {
        delete options.data;
      }
      this._post(blogPath(blogName, '/post'), options, callback);
    };
  },
```
