### ISSUE TITLE
tumblr 사진포스팅시에 다른 tumblr에 post하다 죽는 문제가 발생함.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#228]
tumblr 사진포스팅시에 다른 tumblr에 post하다 죽는 문제가 발생함.
일전에 link post에서 죽는거랑 느낌은 비슷함.

```
info: + cName=tumblr, userId=5549e12f950235140a450656, url=/bot_posts/new/wzdpage?userid=5549e12f950235140a450656&postType=post

/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/node_modules/request/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:41
      stream.on('data', this._checkDataSize.bind(this));
             ^
TypeError: Object [object Object] has no method 'on'
    at FormData.CombinedStream.append (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/node_modules/request/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:41:14)
    at FormData.append (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/node_modules/request/node_modules/form-data/lib/form_data.js:33:3)
    at Object.TumblrClient._post (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/lib/tumblr.js:202:12)
    at Object.text (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/tumblr.js/lib/tumblr.js:36:12)
    at /Users/aleckim/WebstormProjects/BlogSyncer/routes/tumblr.js:561:18
    at Promise.<anonymous> (/Users/aleckim/WebstormProjects/BlogSyncer/controllers/userManager.js:227:9)
    at Promise.<anonymous> (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/aleckim/WebstormProjects/BlogSyncer/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
Process finished with exit code 8
```

**Comment by kimalec** [comment]
tumblr를 기준으로 post방식을 다시 만들고 있음.

botFormat에서 각자 주고 받는 데이터의 양식를 설정하였음.

blogConvert를 통하여, photo, link, 등 다양한 포맷을 textpost로 변경할수 있게 하였음.

BlogSync에서는 text, photo, video, audio, link 5가지 종류만 지원하고, 그외의 종류는 provider에서 변환해서 blogBot으로 보내야 함.

*title은 option으로 변경되었고, key가 되지는 못함.  모아보기에서는 key 사용할 부분이 필요함.*

**Comment by kimalec** [comment]
text 타입에도 tag가 불가능한 페이스북, 카카오스토리가 있고, 가능한 일반 블로그 계열이 있다.
tag가 포함한된 post가 tag 불가능한 곳에는 link로 건다.

**Comment by kimalec** [comment]
test용 data는 test_data에 모았음.

생성시에는 botPost 구조를 쓸 수 있지만, 데이타를 받은 입장에서는 바로 맵핑이 안됨.
