### ISSUE TITLE
ECONNREFUSED 발생. http status code 503

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#334]
blogbot.js에서 각 provider로 blogbot 관련 api를 호출할때 발생함.

tumblr/bot_posts 요청시에 발생한 경우.
``` log
 » 29 Jul 2015 05:05:02.542 2015-07-28 20:05:02.250423+00:00 app web.1 - - verbose: Url=http://www.justwapps.com/tumblr/bot_posts/wizardfactory?after=2015-07-28T20:03:51.644Z&userid=558c10590528f4ac83c0f061 cName=BlogBot, fName=_requestGetPosts, userId=558c10590528f4ac83c0f061
 » 29 Jul 2015 05:05:33.628 2015-07-28 20:05:33.333155+00:00 app web.1 - - error: { [Error: connect ECONNREFUSED] Fatal
» 29 Jul 2015 05:05:33.628 2015-07-28 20:05:33.336517+00:00 app web.1 - - info: - cName=BlogBot, fName=_updateAccessToken, userId=55923da1590d8a11002548f3
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333159+00:00 app web.1 - - code: 'ECONNREFUSED',
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333161+00:00 app web.1 - - errno: 'ECONNREFUSED',
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333162+00:00 app web.1 - - syscall: 'connect',
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333164+00:00 app web.1 - - statusCode: 503,
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333166+00:00 app web.1 - - url: 'http://www.justwapps.com/tumblr/bot_posts/wizardfactory?after=2015-07-28T20:03:51.644Z&userid=558c10590528f4ac83c0f061' } cName=BlogBot, fName=_requestGetPosts, userId=558c10590528f4ac83c0f061
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333751+00:00 app web.1 - - warn: { [Error: connect ECONNREFUSED]
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333753+00:00 app web.1 - - code: 'ECONNREFUSED',
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333755+00:00 app web.1 - - errno: 'ECONNREFUSED',
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333756+00:00 app web.1 - - syscall: 'connect',
» 29 Jul 2015 05:05:33.629 2015-07-28 20:05:33.333758+00:00 app web.1 - - statusCode: 503,
» 29 Jul 2015 05:05:33.630 2015-07-28 20:05:33.333759+00:00 app web.1 - - url: 'http://www.justwapps.com/tumblr/bot_posts/wizardfactory?after=2015-07-28T20:03:51.644Z&userid=558c10590528f4ac83c0f061' } cName=BlogBot, fName=_getAndPush, userId=558c10590528f4ac83c0f061
» 29 Jul 2015 05:05:33.630 2015-07-28 20:05:33.333895+00:00 app web.1 - - warn: Error: connect ECONNREFUSED at exports._errnoException (util.js:746:11) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19) cName=BlogBot, fName=_getAndPush, userId=558c10590528f4ac83c0f061 Exception
```
kakao/bot_posts를 요청시에 발생한 error
```log
 » 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340230+00:00 app web.1 - - error: { [Error: connect ECONNREFUSED] Fatal
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340234+00:00 app web.1 - - code: 'ECONNREFUSED',
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340236+00:00 app web.1 - - errno: 'ECONNREFUSED',
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340238+00:00 app web.1 - - syscall: 'connect',
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340239+00:00 app web.1 - - statusCode: 503,
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340242+00:00 app web.1 - - url: 'http://www.justwapps.com/kakao/bot_posts/4388271?after=2015-07-28T20:03:56.847Z&userid=55923da1590d8a11002548f3' } cName=BlogBot, fName=_requestGetPosts, userId=55923da1590d8a11002548f3
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340621+00:00 app web.1 - - warn: { [Error: connect ECONNREFUSED]
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340624+00:00 app web.1 - - code: 'ECONNREFUSED',
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340627+00:00 app web.1 - - errno: 'ECONNREFUSED',
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340629+00:00 app web.1 - - syscall: 'connect',
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340631+00:00 app web.1 - - statusCode: 503,
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340633+00:00 app web.1 - - url: 'http://www.justwapps.com/kakao/bot_posts/4388271?after=2015-07-28T20:03:56.847Z&userid=55923da1590d8a11002548f3' } cName=BlogBot, fName=_getAndPush, userId=55923da1590d8a11002548f3
» 29 Jul 2015 05:05:33.631 2015-07-28 20:05:33.340739+00:00 app web.1 - - warn: Error: connect ECONNREFUSED at exports._errnoException (util.js:746:11) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19) cName=BlogBot, fName=_getAndPush, userId=55923da1590d8a11002548f3 Exception
```

**Comment by kimalec** [comment]
node.js 안정성과 연관이 있고, blog_bot에서 rest api 형태로 요청하는 것이 아니라, direct function call형태로 변경시에 어느 정도 개선효과를 볼 수 있을 듯하다.
