### ISSUE TITLE
opensift에서 tistory login시에 죽는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#354]
opensift에서 tistory login시에 죽는 문제.

```js
AssertionError: callback must be a function
    at parseOptions (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport-tistory/node_modules/follow-redirects/create.js:117:12)
    at Object.H.request (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport-tistory/node_modules/follow-redirects/create.js:102:22)
    at exports.OAuth2._executeRequest (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/oauth/lib/oauth2.js:132:30)
    at exports.OAuth2._request (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/oauth/lib/oauth2.js:111:8)
    at TistoryStrategy._oauth2.getOAuthAccessToken (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport-tistory/lib/passport-tistory/strategy.js:54:10)
    at TistoryStrategy.OAuth2Strategy.authenticate (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport-tistory/node_modules/passport-oauth2/lib/strategy.js:169:18)
    at attempt (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at Object.authenticate [as handle] (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at next_layer (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/route.js:107:5)
    at /var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:205:24
    at Function.proto.process_params (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:269:12)
    at next (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:199:19)
    at next (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:176:38)
    at Function.proto.handle (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:151:3)
    at Layer.router (/var/lib/openshift/55f035ba2d527171d3000173/app-root/runtime/repo/node_modules/express/lib/router/index.js:24:12)
```

**Comment by kimalec** [comment]
passport-tistory에 사용하는 follow-redirects가 0.0.7이 설치되면서 문제가 발생하는 듯함.

**Comment by kimalec** [comment]
https://github.com/saltfactory/passport-tistory/issues/1 도움 요청 중
